### ISSUE TITLE
Panic on filter query 

### ISSUE THREAD

**Issue by cyrilMargaria** [AsaiYusuke/jsonpath#1]
A panic happens when using a literal compare in a boolean logical operation 

**To Reproduce**
version: df1774fbf7cda6364704fda7c6493ab13907a2f8
Att the following test cases to TestRetrieve_filterExist:
```
                     {
				jsonpath:     `$[?(@.a>1 && (1==2))]`,
				inputJSON:    `[{"a":1},{"a":2},{"a":3}]`,
				expectedJSON: `[]`,
			},  
			  {
				jsonpath:     `$[?(@.a>1 && (1==1))]`,
				inputJSON:    `[{"a":1},{"a":2},{"a":3}]`,
				expectedJSON: `[{"a":2},{"a":3}]`,
			},  
```			
then run 
`go test . -run TestRetrieve_filterExist`

--- FAIL: TestRetrieve_filterExist (0.00s)
    --- FAIL: TestRetrieve_filterExist/child_<$[?(@.a>1_&&_(1==2))]>_<[{"a":1},{"a":2},{"a":3}]> (0.00s)
panic: runtime error: index out of range [1] with length 1 [recovered]
        panic: runtime error: index out of range [1] with length 1

goroutine 567 [running]:
testing.tRunner.func1.2({0x11919a0, 0xc000182630})
        /usr/local/Cellar/go/1.18/libexec/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        /usr/local/Cellar/go/1.18/libexec/src/testing/testing.go:1392 +0x39f
panic({0x11919a0, 0xc000182630})
        /usr/local/Cellar/go/1.18/libexec/src/runtime/panic.go:838 +0x207
github.com/AsaiYusuke/jsonpath.(*syntaxLogicalAnd).compute(0xc0001ef8c0, {0x1171e40, 0xc00060eee8}, {0xc0001c75c0, 0x3, 0x4}, 0x12f66e0?)
        /go/src/jsonpath/syntax_query_logical_and.go:14 +0x130
github.com/AsaiYusuke/jsonpath.(*syntaxFilterQualifier).retrieveList(0xc00060efd8, {0x1171e40, 0xc00060eee8}, {0xc0001c75c0, 0x3, 0x4}, 0xc00060f008)
        /go/src/jsonpath/syntax_node_qualifier_filter.go:96 +0x62
github.com/AsaiYusuke/jsonpath.(*syntaxFilterQualifier).retrieve(0x97?, {0x1171e40?, 0xc00060eee8?}, {0x1171e40?, 0xc00060eee8?}, 0x0?)
        /go/src/jsonpath/syntax_node_qualifier_filter.go:19 +0x9e
github.com/AsaiYusuke/jsonpath.Parse.func2({0x1171e40, 0xc00060eee8})
        /go/src/jsonpath/jsonpath.go:57 +0x77
github.com/AsaiYusuke/jsonpath.Retrieve({0x11a7a90?, 0x1171e40?}, {0x1171e40, 0xc00060eee8}, {0x0?, 0x1178a20?, 0xc0006036d0?})
        /go/src/jsonpath/jsonpath.go:18 +0x64
github.com/AsaiYusuke/jsonpath.execTestRetrieve(0xc0005ba820, {0x1171e40, 0xc00060eee8}, {{0x11a7a90, 0x15}, {0x11a95d6, 0x19}, {0x119fd44, 0x2}, {0x0, ...}, ...})
        /go/src/jsonpath/test_jsonpath_test.go:85 +0x2db
github.com/AsaiYusuke/jsonpath.execTestRetrieveTestGroups.func1(0xc0005ba820)
        /go/src/jsonpath/test_jsonpath_test.go:129 +0x1a5
testing.tRunner(0xc0005ba820, 0xc0005c2000)
        /usr/local/Cellar/go/1.18/libexec/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /usr/local/Cellar/go/1.18/libexec/src/testing/testing.go:1486 +0x35f
FAIL    github.com/AsaiYusuke/jsonpath  0.376s

**Expected behavior**
Test should not panic and pass

**Comment by AsaiYusuke** [comment]
Hi cyrilMargaria,
Thanks for the feedback. I've put the fix and some tests in PR #2, would you like to check it before merging?
